version: '3.1'
services:
  stats-server:
    build: ./stat
    container_name: ewm-stat
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStatDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-postgresql
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmStatDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ./main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STAT-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmMainDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=iamroot

  ewm-db:
    image: postgres:14-alpine
    container_name: main-postgresql
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmMainDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=iamroot
